Repository eikek/docspell, pull requests merged in 2025-01, with the labels that each got.

#2911 These things live over at docspell/docker now
  README.md
  docker/docker-compose/docker-compose.yml
  docker/dockerfiles/build.sh
  docker/dockerfiles/joex-entrypoint.sh
  docker/dockerfiles/joex.dockerfile
  docker/dockerfiles/restserver.dockerfile
  kubernetes/README.md
  kubernetes/deployment.yaml
  kubernetes/ingress.yaml
  kubernetes/kustomization.yaml
  kubernetes/namespace.yaml
  kubernetes/postgres.yaml
  kubernetes/secret.yaml
  kubernetes/service.yaml
  kubernetes/solr.yaml
Labels: chore

#2902 Fix duplicate task on reboot
  modules/joex/src/main/scala/docspell/joex/JoexAppImpl.scala
  modules/joex/src/main/scala/docspell/joex/updatecheck/UpdateCheckTask.scala
Labels: fix

#2941 Correction German Word Dokumene to Dokumente.
  modules/webapp/src/main/elm/Messages/Page/DefaultDashboard.elm
Labels: bug, webui
